services:
  # Main API service
  - type: web
    name: mi-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: mi-api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mi-api-redis
          property: connectionString
      # Supabase configuration (to be set manually in Render dashboard)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      # JWT Secret (to be set manually)
      - key: JWT_SECRET
        sync: false
      # Background Worker configuration (optional)
      - key: WORKER_API_URL
        sync: false
      - key: WORKER_API_TOKEN
        sync: false

  # Redis service for background job processing
  - type: redis
    name: mi-api-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  # PostgreSQL database
databases:
  - name: mi-api-db
    databaseName: mi_api_production
    user: mi_api_user
    plan: free